- name: Install AD-Domain-Services
  win_feature: >
    name=AD-Domain-Services
    include_management_tools=yes
    include_sub_features=yes
    state=present
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required
