---
- name: Active Directory Forests
  hosts: DCs_root
  roles:
    - role: roles/domain_root
  vars_files:
    - vars/vars.yml
    
- name: Active Directory Child Domains
  hosts: DCs_child
  roles:
    - role: roles/domain_child
  vars_files:
    - vars/vars.yml

- name: Active Directory Servers
  hosts: Servers
  roles:
    - role: roles/servers
  vars_files:
    - vars/vars.yml
