- name: Install RDP Services
  win_feature: >
    name=RDS-Licensing,RDS-RD-Server
    include_management_tools=yes
    include_sub_features=yes
    state=present
  register: res
  when: (vars[inventory_hostname].rdp is defined) and (vars[inventory_hostname].rdp == "yes" or vars[inventory_hostname].rdp == true)

- name: Reboot
  win_reboot:
  when: (vars[inventory_hostname].rdp is defined) and (vars[inventory_hostname].rdp == "yes" or vars[inventory_hostname].rdp == true) and (res.reboot_required)
  
- name: Configure RDP Group Policy
  win_user_right:
    name: SeRemoteInteractiveLogonRight
    users: BUILTIN\Remote Desktop Users
    action: add
  when: (vars[inventory_hostname].rdp is defined) and (vars[inventory_hostname].rdp == "yes" or vars[inventory_hostname].rdp == true)
