---

# Manage default configurations for all the VMs
- import_playbook: playbook/common-setup.yml

# Install AD environment in target VMs
- import_playbook: playbook/ad-setup.yml

# Build Forests, Join Child Domains to Forests, Join Servers to Domains
- import_playbook: playbook/ad-build.yml

# Install Extra Features
- import_playbook: playbook/extras.yml

# Import a Scenario:
#- import_playbook: playbook/modules/scenario1.yml
#- import_playbook: playbook/modules/scenario2.yml
- import_playbook: playbook/modules/custom.yml

# Shutdown/Reboot all the VMs
- import_playbook: playbook/shutdown.yml
